name: buildAndDeploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - name: buildAndDeploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT:
          export VUE_APP_ALGO_UUID=${{ secrets.ALGO_UUID }} &&
          export VUE_APP_ALGO_TOKEN=${{ secrets.ALGO_TOKEN }} &&
          npm install &&
          npm run build
